# https://github.com/linhbkhn95/express-gateway-example
# https://github.com/JeniTurtle/express-gateway
# https://hackernoon.com/authentication-middleware-in-express-gateway-using-jwt-km40360p
http:
  port: 8080
#https:
#  port: 8443
#  tls:
#    default:
#        key: /usr/local/share/ca-certificates/ssl.key
#        cert: /usr/local/share/ca-certificates/ssl.crt
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  catalog:
    # methods: 'GET,POST,PUT'
    host: localhost
    paths: [
      '/api/v1/profeco/catalogo/producto',
      '/api/v1/profeco/catalogo/producto/:barcode'
    ]
  review:
    host: localhost
    paths: [
      '/api/v1/profeco/review',
      '/api/v1/profeco/review/:id',
      '/api/v1/profeco/review/:user',
      '/api/v1/profeco/review/:product'
    ]
  wishlist:
    host: localhost
    paths: [
      '/api/v1/profeco/wishlist',
      '/api/v1/profeco/wishlist/:id',
      '/api/v1/profeco/wishlist/:user'
    ]
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  catalogService:
    url: 'http://localhost:3005/'
  reviewService:
    url: 'http://localhost:3010/'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  catalogPipeline:
    apiEndpoints:
      - catalog
    policies:
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: catalogService
              changeOrigin: true
